name: Publish Backend
on:
  push:
    branches:
      - prod
jobs:
  release:
    concurrency: ## sıralı çalışma
      group: ${{ github.ref }}
    runs-on: ubuntu-latest ## github actions üzerinde neyin üzerinde çalışacağı
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master ## action template  https://github.com/appleboy/ssh-action
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: cd /home/debian/backend && git checkout prod && git pull && bash start.sh